# Site settings
title: Shopify Theme Kit
email: themekit@shopify.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/themekit"
url: "https://shopify.github.io"
sass:
  cache: true
themekitversion: "v0.6.3"

# Build settings
markdown: kramdown
